### ISSUE TITLE
[Feature]ShippingAddress

### ISSUE THREAD

**Issue by digetlyn** [Spharos-Academy-5-Team-of-YuSeokKim/Back_Server_Side_App#76]
##주요내용
- 배송지 등록 기능구현

##Todo
-[] : 사용자 정보 등록하면 DB에 등록되는지 보기
-[] : 연락처에서 '  -  ' 필수값으로 받는거.. 이건 프론트에서 할 일인가?
-[] : Swagger에서 실행해보기

**Comment by yuseok-kim-edushare** [comment]
연락처에서 -(하이픈) 받게 하는 거는 프론트에서 Zod 등으로 유효성 검사해서 올려달라고 해야 할 거에요.
(없이 받는다고 문제 생기는 영역은 아니니 백엔드 검사 로직은 필요 없을 거 같아요!)
(+ 해외 전화도 일단은 받을 수 있는 자료형으로 관리중이라서, -이 필수가 아닐 수 있어요)

**Comment by digetlyn** [comment]
넵 확인용
